// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nvg.EmailService.Data;
using Oracle.EntityFrameworkCore.Metadata;

namespace Nvg.EmailService.data.Migrations.OracleMigrations
{
    [DbContext(typeof(EmailOracleDBContext))]
    partial class EmailOracleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailChannelTable", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EmailPoolID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EmailProviderID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Key")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("EmailPoolID");

                    b.HasIndex("EmailProviderID");

                    b.ToTable("EmailChannel");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailHistoryTable", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Attempts")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmailChannelID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EmailProviderID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MessageSent")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Recipients")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sender")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tags")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TemplateName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TemplateVariant")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("EmailChannelID");

                    b.HasIndex("EmailProviderID");

                    b.ToTable("EmailHistory");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailPoolTable", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmailPool");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailProviderSettingsTable", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Configuration")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EmailPoolID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("EmailPoolID");

                    b.ToTable("EmailProviderSettings");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailQuotaTable", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailChannelID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("MonthlyConsumption")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MonthlyQuota")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalConsumption")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("EmailChannelID");

                    b.ToTable("EmailQuota");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailTemplateTable", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("EmailPoolID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sender")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Variant")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.HasIndex("EmailPoolID");

                    b.ToTable("EmailTemplate");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailChannelTable", b =>
                {
                    b.HasOne("Nvg.EmailService.Data.Entities.EmailPoolTable", "EmailPool")
                        .WithMany()
                        .HasForeignKey("EmailPoolID");

                    b.HasOne("Nvg.EmailService.Data.Entities.EmailProviderSettingsTable", "EmailProvider")
                        .WithMany()
                        .HasForeignKey("EmailProviderID");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailHistoryTable", b =>
                {
                    b.HasOne("Nvg.EmailService.Data.Entities.EmailChannelTable", "EmailChannel")
                        .WithMany()
                        .HasForeignKey("EmailChannelID");

                    b.HasOne("Nvg.EmailService.Data.Entities.EmailProviderSettingsTable", "EmailProvider")
                        .WithMany()
                        .HasForeignKey("EmailProviderID");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailProviderSettingsTable", b =>
                {
                    b.HasOne("Nvg.EmailService.Data.Entities.EmailPoolTable", "EmailPool")
                        .WithMany()
                        .HasForeignKey("EmailPoolID");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailQuotaTable", b =>
                {
                    b.HasOne("Nvg.EmailService.Data.Entities.EmailChannelTable", "EmailChannel")
                        .WithMany()
                        .HasForeignKey("EmailChannelID");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailTemplateTable", b =>
                {
                    b.HasOne("Nvg.EmailService.Data.Entities.EmailPoolTable", "EmailPool")
                        .WithMany()
                        .HasForeignKey("EmailPoolID");
                });
#pragma warning restore 612, 618
        }
    }
}
