// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nvg.EmailService.Data;

namespace Nvg.EmailService.Data.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    partial class EmailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Email")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailCounterModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Count")
                        .HasColumnType("text");

                    b.Property<string>("FacilityID")
                        .HasColumnType("text");

                    b.Property<string>("TenantID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("EmailCounter");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailHistoryModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FacilityID")
                        .HasColumnType("text");

                    b.Property<string>("MailBody")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TenantID")
                        .HasColumnType("text");

                    b.Property<string>("ToEmailID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("EmailHistory");
                });

            modelBuilder.Entity("Nvg.EmailService.Data.Entities.EmailTemplateModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmailBodyTemplate")
                        .HasColumnType("text");

                    b.Property<string>("FacilityID")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SubjectTemplate")
                        .HasColumnType("text");

                    b.Property<string>("TenantID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("EmailTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
